MC_GM = MC_GM or {}

MC_GM.Config = {
    port = 25565,
    motd = "GMod cross-play bridge",
    max_players = 32,
    protocol_version = 340,
    minecraft_version = "1.12.2",

    world_scale = 32,
    gmod_origin = Vector(0, 0, 0),
    minecraft_spawn = { x = 0, y = 80, z = 0 },
    spawn_chunk_radius = 3,
    floor_y = 79,
    floor_block_state = 16,
    always_make_spawn_platform = true,
    spawn_platform_radius = 48,
    shared_platform_enabled = true,
    shared_platform_model = "models/hunter/plates/plate8x8.mdl",
    shared_platform_tile_size = 384,
    shared_platform_tiles = 3,
    force_gmod_spawn_to_bridge = true,
    gmod_spawn_offset = Vector(0, 0, 12),
    gmod_spawn_trace_height = 512,
    platform_trace_height = 2048,
    enable_minecraft_player_proxies = true,
    minecraft_proxy_model = "models/player/kleiner.mdl",
    gmod_player_marker_block_state = 656,
    hitbox_block_state = 64,
    hitbox_sync_interval = 1,
    hitbox_sync_radius = 2048,
    max_hitbox_blocks_per_entity = 96,
    max_hitbox_entities_per_scan = 32,
    minecraft_proxy_health = 20,
    minecraft_proxy_hit_radius = 36,
    minecraft_command_range = 512,
    minecraft_crowbar_damage = 12,
    minecraft_blast_damage = 20,
    minecraft_blast_force = 600,

    tick_interval = 0.05,
    position_sync_interval = 0.05,
    keepalive_interval = 10,

    enable_prop_blocks = true,
    prop_scan_interval = 2,
    prop_scan_radius = 4096,
    max_prop_blocks_per_scan = 128,
    prop_block_state = 16
}
