MC_GM = MC_GM or {}

MC_GM.Config = {
    port = 25565,
    motd = "GMod cross-play bridge",
    max_players = 32,
    protocol_version = 340,
    minecraft_version = "1.12.2",
    world_version = 1,

    world_scale = 32,
    gmod_origin = Vector(0, 0, 2048),
    minecraft_spawn = { x = 0, y = 80, z = 0 },
    spawn_chunk_radius = 3,
    floor_y = 79,
    floor_block_state = 16,
    always_make_spawn_platform = true,
    enable_persistent_platform_blocks = false,
    spawn_platform_radius = 48,
    shared_platform_enabled = true,
    shared_platform_model = "models/hunter/plates/plate8x8.mdl",
    shared_platform_tile_size = 384,
    shared_platform_tiles = 3,
    shared_platform_z = -32,
    shared_platform_align_top_to_origin = true,
    shared_platform_surface_z = 0,
    shared_platform_destructible = false,
    force_gmod_spawn_to_bridge = true,
    gmod_spawn_offset = Vector(0, 0, 24),
    gmod_spawn_trace_height = 512,
    platform_trace_height = 2048,
    enable_minecraft_player_proxies = true,
    enable_minecraft_player_visibility = true,
    minecraft_player_spawn_delay = 0.15,
    minecraft_proxy_entity_class = "prop_dynamic",
    minecraft_proxy_model = "models/player/kleiner.mdl",
    minecraft_proxy_mins = Vector(-16, -16, 0),
    minecraft_proxy_maxs = Vector(16, 16, 72),
    enable_minecraft_nametags = true,
    debug_minecraft_movement = false,
    enable_gmod_equipment_sync = true,
    gmod_minecraft_entity_mode = "player",
    gmod_player_spawn_delay = 0.25,
    gmod_player_minecraft_y_offset = 0.75,
    gmod_minecraft_entity_type = 54,
    enable_gmod_player_marker_blocks = false,
    gmod_player_marker_block_state = 656,
    enable_hitbox_blocks = false,
    hitbox_block_state = 16,
    hitbox_fill_blocks = true,
    hitbox_sync_interval = 1,
    hitbox_sync_radius = 2048,
    max_hitbox_blocks_per_entity = 384,
    max_hitbox_entities_per_scan = 32,
    enable_minecraft_block_building = true,
    minecraft_build_block_state = 16,
    minecraft_block_entity_class = "base_anim",
    minecraft_block_model = "models/hunter/blocks/cube025x025x025.mdl",
    minecraft_block_material = "models/debug/debugwhite",
    minecraft_block_color = Color(80, 220, 120, 255),
    minecraft_block_scale = 3,
    minecraft_block_mins = Vector(-16, -16, -16),
    minecraft_block_maxs = Vector(16, 16, 16),
    minecraft_block_solid = true,
    minecraft_block_collide_players = true,
    minecraft_block_soft_player_collision = true,
    minecraft_block_soft_collision_half_size = 16,
    gmod_block_place_range = 512,
    debug_block_packets = true,
    debug_gmod_block_spawns = true,
    chunk_section_radius = 1,
    quiet_minecraft_system_chat = true,
    max_initial_block_replay = 0,
    defer_world_sync_after_login = 1.5,
    defer_world_sync_after_respawn = 0.75,
    send_chunks_on_login = true,
    send_blocks_on_login = true,
    minecraft_proxy_health = 100,
    minecraft_proxy_hit_radius = 56,
    minecraft_proxy_melee_range = 96,
    debug_combat = true,
    minecraft_command_range = 512,
    minecraft_sword_damage = 25,
    minecraft_bow_damage = 20,
    minecraft_crowbar_damage = 25,
    minecraft_blast_damage = 20,
    minecraft_blast_force = 600,

    tick_interval = 0.05,
    position_sync_interval = 0.05,
    keepalive_interval = 10,

    enable_prop_blocks = false,
    prop_scan_interval = 2,
    prop_scan_radius = 4096,
    max_prop_blocks_per_scan = 128,
    prop_block_state = 16,

    -- Minecraft 1.12.2 block states are usually block_id * 16 + metadata.
    -- Replace model/material values with paths from an installed Minecraft block addon.
    minecraft_block_types = {
        [16] = { name = "Stone", item_id = 1, state = 16, color = Color(120, 120, 120, 255) },
        [32] = { name = "Grass", item_id = 2, state = 32, color = Color(90, 170, 70, 255) },
        [48] = { name = "Dirt", item_id = 3, state = 48, color = Color(130, 85, 50, 255) },
        [64] = { name = "Cobblestone", item_id = 4, state = 64, color = Color(105, 105, 105, 255) },
        [80] = { name = "Oak Planks", item_id = 5, state = 80, color = Color(170, 135, 80, 255) },
        [320] = { name = "Glass", item_id = 20, state = 320, color = Color(180, 230, 255, 160), material = "models/debug/debugwhite" }
    },

    minecraft_hotbar_blocks = {
        [3] = 16,
        [4] = 32,
        [5] = 48,
        [6] = 64,
        [7] = 80,
        [8] = 320
    }
}

MC_GM.WorldPath = "mcgm/world.json"
